"""Generated repository policy and hardened Compose templates."""

from __future__ import annotations

from typing import Any

import yaml

GENERATED_POLICY_HEADER = (
    "# Generated by `anaxigraph init`. Edit and commit this repository policy.\n"
    "# Findings are review signals; AnaxiGraph never refactors target code automatically.\n\n"
)


def render_repository_config(
    project_name: str,
    *,
    groups: list[tuple[str, str, str]],
    architecture_policy: str | None,
    coverage_files: list[str],
    semantic_enabled: bool = False,
) -> str:
    value = _repository_policy(
        project_name,
        groups=groups,
        architecture_policy=architecture_policy,
        coverage_files=coverage_files,
        semantic_enabled=semantic_enabled,
    )
    return GENERATED_POLICY_HEADER + yaml.safe_dump(value, sort_keys=False, width=100)


def _repository_policy(
    project_name: str,
    *,
    groups: list[tuple[str, str, str]],
    architecture_policy: str | None,
    coverage_files: list[str],
    semantic_enabled: bool,
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "project": {"name": project_name},
        "architecture": _architecture_policy(groups, architecture_policy),
    }
    if groups:
        value["groups"] = {
            name: {"level": "area", "description": description, "paths": [path]}
            for name, path, description in groups
        }
    value["coverage"] = {"required": False, "files": coverage_files}
    value["agent"] = {"context_limit": 25, "neighbor_depth": 2, "payload_limit_bytes": 20_000}
    value["semantic"] = {
        "enabled": semantic_enabled,
        "provider": "agent",
        "refresh": "manual",
        "max_age_days": 0,
        "max_jobs_per_run": 100,
        "max_parallel_jobs": 1,
        "agent_lease_seconds": 1_800,
    }
    return value


def _architecture_policy(
    groups: list[tuple[str, str, str]], architecture_policy: str | None
) -> dict[str, Any]:
    source_paths = [
        path
        for name, path, _ in groups
        if name not in {"testing", "documentation", "developer-tooling", "infrastructure"}
    ]
    architecture: dict[str, Any] = {
        "rules": [
            {
                "id": "module-size-review",
                "type": "max_module_loc",
                "severity": "info",
                "description": "Review source modules above 500 physical lines for cohesion.",
                "max": 500,
                **({"paths": source_paths} if source_paths else {}),
            },
            {
                "id": "symbol-complexity-review",
                "type": "max_symbol_complexity",
                "severity": "warning",
                "max": 15,
            },
            {
                "id": "dependency-cycle-review",
                "type": "no_cycles",
                "severity": "warning",
            },
        ]
    }
    if architecture_policy:
        architecture = {"policy": architecture_policy, **architecture}
    return architecture


def render_compose(
    *,
    project_slug_value: str,
    image: str,
    port: int,
    history_snapshots: int | str,
) -> str:
    return "".join(
        (
            _compose_base(project_slug_value, image),
            _compose_app(port, history_snapshots),
            _compose_volume(history_snapshots),
        )
    )


def _compose_base(project_slug_value: str, image: str) -> str:
    return f"""# Generated by `anaxigraph init`. The repository mount is read-only.
name: anaxigraph-{project_slug_value}

x-anaxigraph-service: &anaxigraph-service
  image: ${{ANAXIGRAPH_IMAGE:-{image}}}
  init: true
  read_only: true
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL
  tmpfs:
    - /tmp:size=128m,mode=1777
  environment:
    ANAXIGRAPH_WATCH_INTERVAL: "${{ANAXIGRAPH_WATCH_INTERVAL:-10}}"
  volumes:
    - type: bind
      source: .
      target: /repo
      read_only: true
    - type: volume
      source: anaxi_index
      target: /state
  restart: unless-stopped

"""


def _compose_app(port: int, history_snapshots: int | str) -> str:
    return f"""services:
  anaxigraph:
    <<: *anaxigraph-service
    command:
      - serve
      - --repository
      - /repo
      - --db
      - /state/anaxi-index.db
      - --host
      - 0.0.0.0
      - --port
      - "8765"
      - --history-snapshots
      - "{history_snapshots}"
      - --allow-agent-scan
    ports:
      - "127.0.0.1:${{ANAXIGRAPH_PORT:-{port}}}:8765"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8765/healthz', timeout=3).read()"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 300s

"""


def _compose_volume(history_snapshots: int | str) -> str:
    return f"""volumes:
  anaxi_index:

# AnaxiGraph uses the {history_snapshots} history-frame policy in the background after startup.
"""
